#pragma once

#include "NativeGameplayTags.h"

/**
 * 全项目 GameplayTag 的唯一声明处。
 * 用原生 Tag 而非字符串查询，编译期即可捕获拼写错误。
 */
namespace CCTags
{
	// 角色状态
	CORECOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Attacking);
	CORECOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Dodging);
	CORECOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_HitReacting);
	CORECOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Immobilized);
	CORECOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Dead);
	CORECOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Invincible);
	CORECOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_PerfectDodgeWindow);

	// 能力标识
	CORECOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Light);
	CORECOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Heavy);
	CORECOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Charged);
	CORECOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Dodge);
	CORECOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Spell_Immobilize);

	// 事件
	CORECOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Hit_Received);
	CORECOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Combo_Advance);
	CORECOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_PerfectDodge);

	// 增益
	CORECOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Buff_PerfectDodgeFollowUp);

	// 输入屏蔽
	CORECOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Block_Input);

	// SetByCaller 数据通道
	CORECOMBAT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Damage);
}
